#  i have already knoe numpy basics fromits main web just practicing again

# creatimg an array using numpy

In [3]:
import numpy as np
a = np.array(["pakora", "samosa", "raita"])
a

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price = np.array([5,5,5,])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(a)

numpy.ndarray

In [7]:
len(a)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
a[1]

'samosa'

In [12]:
price.mean(0)

5.0

In [13]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(47)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.empty(76)

array([9.65336682e-312, 9.65344485e-312, 9.65344524e-312, 9.65344511e-312,
       9.65344511e-312, 9.65344511e-312, 9.65344511e-312, 9.65344510e-312,
       9.65344510e-312, 9.65344512e-312, 9.65344510e-312, 9.65344510e-312,
       9.65344508e-312, 9.65344508e-312, 9.65344506e-312, 9.65344505e-312,
       9.65344505e-312, 9.65344505e-312, 9.65344505e-312, 9.65344505e-312,
       9.65344532e-312, 9.65344532e-312, 9.65344532e-312, 9.65344532e-312,
       9.65344532e-312, 9.65344532e-312, 9.65344532e-312, 9.65344532e-312,
       9.65344532e-312, 9.65344532e-312, 9.65344532e-312, 9.65346440e-312,
       9.65346243e-312, 9.65346243e-312, 9.65346243e-312, 9.65346243e-312,
       9.65345993e-312, 9.65345993e-312, 9.65345992e-312, 9.65345998e-312,
       9.65345999e-312, 9.65345998e-312, 9.65345998e-312, 9.65345999e-312,
       9.65346246e-312, 9.65346247e-312, 9.65346247e-312, 9.65346247e-312,
       9.65346248e-312, 9.65346253e-312, 9.65346253e-312, 9.65346254e-312,
       9.65346002e-312, 9

In [17]:
np.arange(12) # last word is always exclusive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# specifying th range # last number showing the gap  meens faraq se in the language of baba g
np.arange(3, 56,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54])

In [20]:
# practicing again the line space
np.linspace(1, 500, num=45)

array([  1.        ,  12.34090909,  23.68181818,  35.02272727,
        46.36363636,  57.70454545,  69.04545455,  80.38636364,
        91.72727273, 103.06818182, 114.40909091, 125.75      ,
       137.09090909, 148.43181818, 159.77272727, 171.11363636,
       182.45454545, 193.79545455, 205.13636364, 216.47727273,
       227.81818182, 239.15909091, 250.5       , 261.84090909,
       273.18181818, 284.52272727, 295.86363636, 307.20454545,
       318.54545455, 329.88636364, 341.22727273, 352.56818182,
       363.90909091, 375.25      , 386.59090909, 397.93181818,
       409.27272727, 420.61363636, 431.95454545, 443.29545455,
       454.63636364, 465.97727273, 477.31818182, 488.65909091,
       500.        ])

In [ ]:
# if you want to sort some array name fg haha then type haha.sort()

In [29]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,2,3,4,5,6,7,8])
c = np.concatenate((a,b))


In [30]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,2,3,4,5,6,7,8])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# 2-D Arrays


In [34]:
uva= np.array([[1,2,3,4,5],[5,4,3,2,1]])
jva= np.array([[6,7,8,9,10],[10,9,8,7,6]])

In [37]:
lva = np.concatenate((uva,jva), axis=0)
lva

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [38]:
lva = np.concatenate((uva,jva), axis=1)
lva

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [40]:
lva = uva + jva 
lva # value sums on the axis 1

array([[ 7,  9, 11, 13, 15],
       [15, 13, 11,  9,  7]])

In [41]:
lva.ndim

2

In [42]:
b= np.array([[5,6,7,],
            [8,9,10],
            [11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [43]:
b.ndim


2

In [44]:
b.shape

(3, 3)

In [ ]:
# cheking shape farmula dim, lines ad numbers inside them


In [47]:
# reshaping
rs = np.arange(48)
rs


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [48]:
rs.reshape(12,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [51]:
# how to convert 1d array into 2d
td = np.array([1,2,3,4,5,6,7,8,9])
td


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# rowwise conversion
tu = td[np.newaxis, :]
tu

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
tu.shape

(1, 9)

In [55]:
# columnwise conversion
tu = td[:, np.newaxis]
tu

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])